services:
  app:
    build: .
    environment:
      - CLOCKIFY_API_KEY
      - CLOCKIFY_WORKSPACE_ID
      - OIDC_RP_CLIENT_ID
      - OIDC_RP_CLIENT_SECRET
      - OIDC_OP_AUTHORIZATION_ENDPOINT
      - OIDC_OP_TOKEN_ENDPOINT
      - OIDC_OP_USER_ENDPOINT
      - OIDC_OP_JWKS_ENDPOINT
      - OIDC_RP_SCOPES
    command:
      - sh
      - -c
      - |
        python manage.py migrate
        python manage.py run_huey &
        python manage.py runserver 0:8000
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/usr/src/app
      - db:/usr/src/app/db
volumes:
  db:
